from graphviz import Digraph

G = Digraph(format='pdf')
G.attr('node', shape='box')

G.node('Apx', 'Appendix', style='dashed', shape='oval')
G.node('ch1', 'Chapter 1: Mathematics and Python')
G.node('ch2', 'Chapter 2: Linear Space and Linear Mapping')
G.node('ch3', 'Chapter 3: Basis and Dimension')
G.node('ch4', 'Chapter 4: Matrix')
G.node('ch5', 'Chapter 5: Elementary Operation and Matrix Invariants')
G.node('ch6', 'Chapter 6: Inner Product and Fourier Expansion')
G.node('ch7', 'Chapter 7: Eigenvalue and Eigenvector')
G.node('ch8', 'Chapter 8: Jordan Normal Form and Spectrum')
G.node('ch9', 'Chapter 9: Dynamical System')
G.node('ch10', 'Chapter 10: Applications and Development of Linear Algebra')

G.edge('Apx', 'ch1', style='dashed', arrowhead='empty')
G.edge('ch1', 'ch2')
G.edge('ch2', 'ch3')
G.edge('ch2', 'ch6')
G.edge('ch3', 'ch4')
G.edge('ch4', 'ch5')
G.edge('ch4', 'ch6')
G.edge('ch5', 'ch7')
G.edge('ch5', 'ch10')
G.edge('ch6', 'ch7')
G.edge('ch6', 'ch8')
G.edge('ch6', 'ch10')
G.edge('ch7', 'ch8')
G.edge('ch7', 'ch10')
G.edge('ch8', 'ch9')

G.render('diagram')
